//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namava_Direct_Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_main_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_main_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Namava_Direct_Downloader.Properties.Resources_main_en", typeof(Resources_main_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Failed!.
        /// </summary>
        internal static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Create Folder!.
        /// </summary>
        internal static string CantCreateFolder {
            get {
                return ResourceManager.GetString("CantCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error!.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string desAdvanced {
            get {
                return ResourceManager.GetString("desAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $N replaces the video name, $Q replaces the video quality, $S the season number, and $E the episode number. You can write this in any format..
        /// </summary>
        internal static string desAdvFormatInfo {
            get {
                return ResourceManager.GetString("desAdvFormatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string desAdvFormatReset {
            get {
                return ResourceManager.GetString("desAdvFormatReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview: .
        /// </summary>
        internal static string desAdvPreviewT {
            get {
                return ResourceManager.GetString("desAdvPreviewT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Format: .
        /// </summary>
        internal static string desAdvSaveFormat {
            get {
                return ResourceManager.GetString("desAdvSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string desAdvTitle {
            get {
                return ResourceManager.GetString("desAdvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allways Mix Files.
        /// </summary>
        internal static string desAllwaysMixFiles {
            get {
                return ResourceManager.GetString("desAllwaysMixFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update the app.
        /// </summary>
        internal static string desAutoUpdate {
            get {
                return ResourceManager.GetString("desAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Numbers to English.
        /// </summary>
        internal static string desChangeNumbers {
            get {
                return ResourceManager.GetString("desChangeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeSaveFromat.
        /// </summary>
        internal static string desChangeSaveFromat {
            get {
                return ResourceManager.GetString("desChangeSaveFromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Save Path.
        /// </summary>
        internal static string desChangeSavePath {
            get {
                return ResourceManager.GetString("desChangeSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string desCopy {
            get {
                return ResourceManager.GetString("desCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string desCreationDate {
            get {
                return ResourceManager.GetString("desCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audios.
        /// </summary>
        internal static string desDelAudios {
            get {
                return ResourceManager.GetString("desDelAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete After Mix.
        /// </summary>
        internal static string desDeleteAfterMix {
            get {
                return ResourceManager.GetString("desDeleteAfterMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Video Folder.
        /// </summary>
        internal static string desDeleteVideoFolder {
            get {
                return ResourceManager.GetString("desDeleteVideoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        internal static string desDelSubtitles {
            get {
                return ResourceManager.GetString("desDelSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string desDelVideo {
            get {
                return ResourceManager.GetString("desDelVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download!.
        /// </summary>
        internal static string desDownload {
            get {
                return ResourceManager.GetString("desDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Audios.
        /// </summary>
        internal static string desDownloadAudios {
            get {
                return ResourceManager.GetString("desDownloadAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Subtitles.
        /// </summary>
        internal static string desDownloadSubtitles {
            get {
                return ResourceManager.GetString("desDownloadSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Video.
        /// </summary>
        internal static string desDownloadVideo {
            get {
                return ResourceManager.GetString("desDownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string desExpirationDate {
            get {
                return ResourceManager.GetString("desExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string desFile {
            get {
                return ResourceManager.GetString("desFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string desHelp {
            get {
                return ResourceManager.GetString("desHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string desLanguage {
            get {
                return ResourceManager.GetString("desLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string desLicense {
            get {
                return ResourceManager.GetString("desLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Information.
        /// </summary>
        internal static string desLicenseInfo {
            get {
                return ResourceManager.GetString("desLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string desOptions {
            get {
                return ResourceManager.GetString("desOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string desPause {
            get {
                return ResourceManager.GetString("desPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Namava Intro.
        /// </summary>
        internal static string desRemoveIntro {
            get {
                return ResourceManager.GetString("desRemoveIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset License.
        /// </summary>
        internal static string desResetLicense {
            get {
                return ResourceManager.GetString("desResetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Days.
        /// </summary>
        internal static string desTotalDays {
            get {
                return ResourceManager.GetString("desTotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed!.
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Error!.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found!.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Not Found!.
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixing Files into one mp4 file....
        /// </summary>
        internal static string MixingFiles {
            get {
                return ResourceManager.GetString("MixingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, activating the application failed.
        ///{0}
        ///
        ///Do you want to try again?.
        /// </summary>
        internal static string msgActivationFailed {
            get {
                return ResourceManager.GetString("msgActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the new version was canceled by user!.
        /// </summary>
        internal static string msgCanceledUpdate {
            get {
                return ResourceManager.GetString("msgCanceledUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected could not be created. Please select a correct folder..
        /// </summary>
        internal static string msgCantCreateFolder {
            get {
                return ResourceManager.GetString("msgCantCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was a connection error when sending the request to Namava. please try again later..
        /// </summary>
        internal static string msgConnectionError {
            get {
                return ResourceManager.GetString("msgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed! files saved on
        ///{0}.
        /// </summary>
        internal static string msgDownloadCompleted {
            get {
                return ResourceManager.GetString("msgDownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error while downloading the file from namava. Please try again!.
        /// </summary>
        internal static string msgDownloadError {
            get {
                return ResourceManager.GetString("msgDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an unhandled error!
        ///Error successfully reported for help..
        /// </summary>
        internal static string msgErrorReported {
            get {
                return ResourceManager.GetString("msgErrorReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the new version encountered an error! Please run this app as an administrator and try again..
        /// </summary>
        internal static string msgFailedUpdate {
            get {
                return ResourceManager.GetString("msgFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} not found, please try again later or skip downloading the file..
        /// </summary>
        internal static string msgFileNotFound {
            get {
                return ResourceManager.GetString("msgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected as save patch was not found. Do you want to create it?.
        /// </summary>
        internal static string msgFolderNotFound {
            get {
                return ResourceManager.GetString("msgFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed! files saved on
        ///{0}
        ///
        ///Do you want to mix files into one mp4 file and close the app?.
        /// </summary>
        internal static string msgMixNeeded {
            get {
                return ResourceManager.GetString("msgMixNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is going to be downloaded. Please Select something to download!.
        /// </summary>
        internal static string msgNothingSelected {
            get {
                return ResourceManager.GetString("msgNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, This app does not have the required permissions, please run it as an administrator..
        /// </summary>
        internal static string msgPermissionError {
            get {
                return ResourceManager.GetString("msgPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please report this error to aam.products.mail@gmail.com for help..
        /// </summary>
        internal static string msgPleaseReport {
            get {
                return ResourceManager.GetString("msgPleaseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset this license? (This will open the license for all computers, if you don&apos;t heve a copy of license code, YOU WILL LOSE YOUR LICENSE).
        /// </summary>
        internal static string msgResetLicense {
            get {
                return ResourceManager.GetString("msgResetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is an error while requesting license info from the server! Please try again!.
        /// </summary>
        internal static string msgServerError {
            get {
                return ResourceManager.GetString("msgServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is downloading several files, do you want to cancel the downloads and close the program?.
        /// </summary>
        internal static string msgStillDownloading {
            get {
                return ResourceManager.GetString("msgStillDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version installed successfully, Please close and reopen this app to apply the update..
        /// </summary>
        internal static string msgSuccessfulUpdate {
            get {
                return ResourceManager.GetString("msgSuccessfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Namava Direct Downloader detected an unhandled error!.
        /// </summary>
        internal static string msgUnhandledError {
            get {
                return ResourceManager.GetString("msgUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install update now?.
        /// </summary>
        internal static string msgUpdateAvailable {
            get {
                return ResourceManager.GetString("msgUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected as save path is wrong. Please select a correct folder!.
        /// </summary>
        internal static string msgWrongFolder {
            get {
                return ResourceManager.GetString("msgWrongFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Selected!.
        /// </summary>
        internal static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Error!.
        /// </summary>
        internal static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for download....
        /// </summary>
        internal static string ReadyForDownload {
            get {
                return ResourceManager.GetString("ReadyForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset License!.
        /// </summary>
        internal static string ResetLicense {
            get {
                return ResourceManager.GetString("ResetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error!.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Download....
        /// </summary>
        internal static string StartingDownalod {
            get {
                return ResourceManager.GetString("StartingDownalod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still Downloading!.
        /// </summary>
        internal static string StillDownloading {
            get {
                return ResourceManager.GetString("StillDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Update....
        /// </summary>
        internal static string strInstallingUpdate {
            get {
                return ResourceManager.GetString("strInstallingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Update!.
        /// </summary>
        internal static string SuccessfulUpdate {
            get {
                return ResourceManager.GetString("SuccessfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error!.
        /// </summary>
        internal static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available!.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error!.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Folder!.
        /// </summary>
        internal static string WrongFolder {
            get {
                return ResourceManager.GetString("WrongFolder", resourceCulture);
            }
        }
    }
}
