//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namava_Direct_Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_main_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_main_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Namava_Direct_Downloader.Properties.Resources_main_fa", typeof(Resources_main_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال سازی انجام نشد!.
        /// </summary>
        internal static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمی توان پوشه ایجاد کرد!.
        /// </summary>
        internal static string CantCreateFolder {
            get {
                return ResourceManager.GetString("CantCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اتصال!.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنضیمات پیشرفته.
        /// </summary>
        internal static string desAdvanced {
            get {
                return ResourceManager.GetString("desAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $N جایگزین نام ویدیو، $Q جایگزین کیفیت ویدیو، $S شماره فصل و $E شماره قسمت می‌شود. شما می توانید این را در هر شکلی بنویسید..
        /// </summary>
        internal static string desAdvFormatInfo {
            get {
                return ResourceManager.GetString("desAdvFormatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی.
        /// </summary>
        internal static string desAdvFormatReset {
            get {
                return ResourceManager.GetString("desAdvFormatReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نمایش: .
        /// </summary>
        internal static string desAdvPreviewT {
            get {
                return ResourceManager.GetString("desAdvPreviewT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ذخیره سازی: .
        /// </summary>
        internal static string desAdvSaveFormat {
            get {
                return ResourceManager.GetString("desAdvSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنضیمات پیشرفته.
        /// </summary>
        internal static string desAdvTitle {
            get {
                return ResourceManager.GetString("desAdvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همیشه فایل ها را میکس کن.
        /// </summary>
        internal static string desAllwaysMixFiles {
            get {
                return ResourceManager.GetString("desAllwaysMixFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به‌روزرسانی خودکار برنامه.
        /// </summary>
        internal static string desAutoUpdate {
            get {
                return ResourceManager.GetString("desAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر اعداد به انگلیسی.
        /// </summary>
        internal static string desChangeNumbers {
            get {
                return ResourceManager.GetString("desChangeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر فرمت ذخیره سازی.
        /// </summary>
        internal static string desChangeSaveFromat {
            get {
                return ResourceManager.GetString("desChangeSaveFromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر محل ذخیره ی فایل ها.
        /// </summary>
        internal static string desChangeSavePath {
            get {
                return ResourceManager.GetString("desChangeSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی.
        /// </summary>
        internal static string desCopy {
            get {
                return ResourceManager.GetString("desCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        internal static string desCreationDate {
            get {
                return ResourceManager.GetString("desCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل های صوتی.
        /// </summary>
        internal static string desDelAudios {
            get {
                return ResourceManager.GetString("desDelAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پس از میکس فایل ها را حذف کنید.
        /// </summary>
        internal static string desDeleteAfterMix {
            get {
                return ResourceManager.GetString("desDeleteAfterMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه ی ویدیو را حذف کن.
        /// </summary>
        internal static string desDeleteVideoFolder {
            get {
                return ResourceManager.GetString("desDeleteVideoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرنویس.
        /// </summary>
        internal static string desDelSubtitles {
            get {
                return ResourceManager.GetString("desDelSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلم ها.
        /// </summary>
        internal static string desDelVideo {
            get {
                return ResourceManager.GetString("desDelVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود!.
        /// </summary>
        internal static string desDownload {
            get {
                return ResourceManager.GetString("desDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود صوت ها.
        /// </summary>
        internal static string desDownloadAudios {
            get {
                return ResourceManager.GetString("desDownloadAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود زیرنویس ها.
        /// </summary>
        internal static string desDownloadSubtitles {
            get {
                return ResourceManager.GetString("desDownloadSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود ویدیو.
        /// </summary>
        internal static string desDownloadVideo {
            get {
                return ResourceManager.GetString("desDownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضا.
        /// </summary>
        internal static string desExpirationDate {
            get {
                return ResourceManager.GetString("desExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل.
        /// </summary>
        internal static string desFile {
            get {
                return ResourceManager.GetString("desFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمک.
        /// </summary>
        internal static string desHelp {
            get {
                return ResourceManager.GetString("desHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        internal static string desLanguage {
            get {
                return ResourceManager.GetString("desLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لایسنس.
        /// </summary>
        internal static string desLicense {
            get {
                return ResourceManager.GetString("desLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات لایسنس.
        /// </summary>
        internal static string desLicenseInfo {
            get {
                return ResourceManager.GetString("desLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه ها.
        /// </summary>
        internal static string desOptions {
            get {
                return ResourceManager.GetString("desOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکث.
        /// </summary>
        internal static string desPause {
            get {
                return ResourceManager.GetString("desPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف معرفی نماوا.
        /// </summary>
        internal static string desRemoveIntro {
            get {
                return ResourceManager.GetString("desRemoveIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی لایسنس.
        /// </summary>
        internal static string desResetLicense {
            get {
                return ResourceManager.GetString("desResetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل روزها.
        /// </summary>
        internal static string desTotalDays {
            get {
                return ResourceManager.GetString("desTotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام شد!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود کامل شد!.
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در دانلود!.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال دانلود.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل یافت نشد!.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه پیدا نشد!.
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال تبدیل فایل ها به یک فایل....
        /// </summary>
        internal static string MixingFiles {
            get {
                return ResourceManager.GetString("MixingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش، فعال سازی برنامه انجام نشد.
        ///{0}
        ///
        ///آیا می خواهید دوباره امتحان کنید؟.
        /// </summary>
        internal static string msgActivationFailed {
            get {
                return ResourceManager.GetString("msgActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب ورژن جدید برنامه توسط کاربر متوقف شد!.
        /// </summary>
        internal static string msgCanceledUpdate {
            get {
                return ResourceManager.GetString("msgCanceledUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه ای که انتخاب کردید ایجاد نشد. لطفا یک پوشه صحیح را انتخاب کنید..
        /// </summary>
        internal static string msgCantCreateFolder {
            get {
                return ResourceManager.GetString("msgCantCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش، هنگام ارسال درخواست به نماوا خطایی وجود داشت. لطفا بعدا دوباره امتحان کنید.
        /// </summary>
        internal static string msgConnectionError {
            get {
                return ResourceManager.GetString("msgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود کامل شد! فایل های ذخیره شده در
        ///{0}.
        /// </summary>
        internal static string msgDownloadCompleted {
            get {
                return ResourceManager.GetString("msgDownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش، هنگام دانلود فایل از نماوا خطایی روی داد. لطفا دوباره تلاش کنید!.
        /// </summary>
        internal static string msgDownloadError {
            get {
                return ResourceManager.GetString("msgDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش، یک خطای کنترل نشده وجود داشت،
        ///خطا برای کمک با موفقیت گزارش شد..
        /// </summary>
        internal static string msgErrorReported {
            get {
                return ResourceManager.GetString("msgErrorReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب نسخه جدید با خطا مواجه شد! لطفاً این برنامه را به عنوان مدیر اجرا کنید و دوباره امتحان کنید..
        /// </summary>
        internal static string msgFailedUpdate {
            get {
                return ResourceManager.GetString("msgFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفیم، {0} یافت نشد، لطفاً بعداً دوباره امتحان کنید یا از دانلود فایل صرفنظر کنید..
        /// </summary>
        internal static string msgFileNotFound {
            get {
                return ResourceManager.GetString("msgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه ای که به عنوان محل ذخیره انتخاب کردید وجود ندارد. آیا می خواهید ان را بسازید؟.
        /// </summary>
        internal static string msgFolderNotFound {
            get {
                return ResourceManager.GetString("msgFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود کامل شد! فایل های ذخیره شده در
        ///{0}
        ///
        ///آیا می خواهید فایل ها را در یک فایل ام پی فور ترکیب کنید و برنامه را ببندید؟.
        /// </summary>
        internal static string msgMixNeeded {
            get {
                return ResourceManager.GetString("msgMixNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرار نیست چیزی دانلود شود. لطفا چیزی را برای دانلود انتخاب کنید!.
        /// </summary>
        internal static string msgNothingSelected {
            get {
                return ResourceManager.GetString("msgNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفیم، این برنامه مجوزهای لازم را ندارد، لطفاً آن را به عنوان مدیر اجرا کنید..
        /// </summary>
        internal static string msgPermissionError {
            get {
                return ResourceManager.GetString("msgPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً این خطا را برای دریافت راهنمایی به aam.products.mail@gmail.com گزارش دهید..
        /// </summary>
        internal static string msgPleaseReport {
            get {
                return ResourceManager.GetString("msgPleaseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید این لایسنس را بازنشانی کنید؟ (با این کار لایسنس برای همه رایانه ها باز می شود، اگر یک کپی از کد آن نداشته باشید، لایسنس خود را از دست خواهید داد!).
        /// </summary>
        internal static string msgResetLicense {
            get {
                return ResourceManager.GetString("msgResetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش، هنگام درخواست اطلاعات مجوز از سرور خطایی روی داد! لطفا دوباره تلاش کنید!.
        /// </summary>
        internal static string msgServerError {
            get {
                return ResourceManager.GetString("msgServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این برنامه در حال دانلود چندین فایل است، آیا می خواهید دانلودها را لغو کنید و برنامه را ببندید؟.
        /// </summary>
        internal static string msgStillDownloading {
            get {
                return ResourceManager.GetString("msgStillDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه جدید با موفقیت نصب شد، لطفاً این برنامه را ببندید و دوباره باز کنید تا بروزرسانی اعمال شود..
        /// </summary>
        internal static string msgSuccessfulUpdate {
            get {
                return ResourceManager.GetString("msgSuccessfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش، دانلودر مستقیم نماوا یک خطای کنترل نشده را شناسایی کرد!.
        /// </summary>
        internal static string msgUnhandledError {
            get {
                return ResourceManager.GetString("msgUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا می خواهید اکنون به روز رسانی را نصب کنید؟.
        /// </summary>
        internal static string msgUpdateAvailable {
            get {
                return ResourceManager.GetString("msgUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه ای که به عنوان مسیر ذخیره انتخاب کرده اید اشتباه است. لطفا یک پوشه صحیح را انتخاب کنید!.
        /// </summary>
        internal static string msgWrongFolder {
            get {
                return ResourceManager.GetString("msgWrongFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ چیز انتخاب نشده است!.
        /// </summary>
        internal static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای مجوز!.
        /// </summary>
        internal static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آماده برای دانلود....
        /// </summary>
        internal static string ReadyForDownload {
            get {
                return ResourceManager.GetString("ReadyForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی مجوز!.
        /// </summary>
        internal static string ResetLicense {
            get {
                return ResourceManager.GetString("ResetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سرور!.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع دانلود....
        /// </summary>
        internal static string StartingDownalod {
            get {
                return ResourceManager.GetString("StartingDownalod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنوز در حال دانلود!.
        /// </summary>
        internal static string StillDownloading {
            get {
                return ResourceManager.GetString("StillDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال نصب آپدیت....
        /// </summary>
        internal static string strInstallingUpdate {
            get {
                return ResourceManager.GetString("strInstallingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپدیت.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی موفقیت آمیز بود!.
        /// </summary>
        internal static string SuccessfulUpdate {
            get {
                return ResourceManager.GetString("SuccessfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای کنترل نشده!.
        /// </summary>
        internal static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی در دسترس است!.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در آپدیت!.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه اشتباه است!.
        /// </summary>
        internal static string WrongFolder {
            get {
                return ResourceManager.GetString("WrongFolder", resourceCulture);
            }
        }
    }
}
